title: Thang Nguyen
email: nm.thang@outlook.com
description: >-
  I code and crack!
baseurl: ""
url: ""
github_username: thang-nm

remote_theme: thang-nm/mindark
plugins:
  - jekyll-feed
  - jekyll-seo-tag
